# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /CalcApiCodeInside_

# copy csproj and restore as distinct layers
COPY *.sln .
COPY CalcApiCodeInside_/*.csproj ./CalcApiCodeInside_/
RUN dotnet restore

# copy everything else and build app
COPY CalcApiCodeInside_/. ./CalcApiCodeInside_/
WORKDIR /CalcApiCodeInside_
RUN dotnet publish -c release -o /app --no-restore

#final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 
WORKDIR /CalcApiCodeInside_
COPY --from=build /app ./
ENTRYPOINT ["dotnet","alcApiCodeInside_.dll"]
